@startuml
'https://plantuml.com/sequence-diagram

autonumber

DataManager -> TidePredictions : Load
TidePredictions -> TideRetriever : Retrieve
TidePredictions <- TideRetriever : std::string
TidePredictions -> TideDataParser : Parse(std::string)
TidePredictions <- TideDataParser : std::vector<TimeSeriesDataPoint>
DataManager <- TidePredictions : TidePredictions

loop config->getDaysToDisplay() times
    DataManager -> TidePredictions : TideLevelsForDate(date)

    TidePredictions -> TimeSeriesDataPoint : ValuesForDate(std::vector<TimeSeriesDataPoint>, date)
    TidePredictions <- TimeSeriesDataPoint : std::vector<TimeSeriesDataPoint>

    TidePredictions -> TimeSeriesDataPoint : MinValue(std::vector<TimeSeriesDataPoint>)
    TidePredictions <- TimeSeriesDataPoint : MinValue(TimeSeriesDataPoint)

    TidePredictions -> TimeSeriesDataPoint : MinValue(std::vector<TimeSeriesDataPoint>)
    TidePredictions <- TimeSeriesDataPoint : MinValue(TimeSeriesDataPoint)

    DataManager <- TidePredictions : TideData

    note left : TideData instance appended to DailyPredictions
end

@enduml

